name: Actualizar Lista IPTV

on:
  schedule:
    - cron: '5 18 * * *' # Todos los días a las 12:00 PM (UTC-6 Centroamérica)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias y Navegador Playwright
        run: |
          pip install requests PyGithub playwright
          playwright install chromium
          
      - name: Ejecutar script de actualización
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          python script.py
