name: Actualizar Lista IPTV

on:
  schedule:
    # Se ejecuta TODOS LOS DÍAS a las 18:00 UTC (12:00 PM Hora Centroamérica)
    - cron: '0 18 * * *'
  
  # Mantiene la opción de ejecutarlo manualmente cuando quieras
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias
        run: |
          pip install requests PyGithub
          
      - name: Ejecutar script de actualización
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          python script.py
